'use strict';

module.exports=Object.freeze({
    '3g2'       : 'video/3gpp2',
    '3gp'       : 'video/3gpp',
    '7z'        : 'application/x-7z-compressed',
    aac         : 'audio/aac',
    abw         : 'application/x-abiword',
    apng        : 'image/apng',
    appcache    : 'text/cache-manifest; charset=utf-8',
    arc         : 'application/x-freearc',
    atom        : 'application/atom+xml; charset=utf-8',
    avif        : 'image/avif',
    avi         : 'video/x-msvideo',
    azw         : 'application/vnd.amazon.ebook',
    bin         : 'application/octet-stream',
    bmp         : 'image/bmp',
    br          : 'application/x-brotli',
    bz          : 'application/x-bzip',
    bz2         : 'application/x-bzip2',
    cjs         : 'text/javascript; charset=utf-8',
    css         : 'text/css; charset=utf-8',
    csv         : 'text/csv; charset=utf-8',
    doc         : 'application/msword',
    docx        : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    eot         : 'application/vnd.ms-fontobject',
    epub        : 'application/epub+zip',
    flac        : 'audio/flac',
    gif         : 'image/gif',
    gz          : 'application/gzip',
    htm         : 'text/html; charset=utf-8',
    html        : 'text/html; charset=utf-8',
    heic        : 'image/heic',
    heif        : 'image/heif',
    ico         : 'image/x-icon',
    ics         : 'text/calendar; charset=utf-8',
    jar         : 'application/java-archive',
    jpeg        : 'image/jpeg',
    jpg         : 'image/jpeg',
    js          : 'text/javascript; charset=utf-8',
    json        : 'application/json; charset=utf-8',
    jsonld      : 'application/ld+json; charset=utf-8',
    m4a         : 'audio/mp4',
    m4v         : 'video/mp4',
    map         : 'application/json; charset=utf-8',
    md          : 'text/markdown; charset=utf-8',
    mid         : 'audio/midi',
    midi        : 'audio/midi',
    mjs         : 'text/javascript; charset=utf-8',
    mp3         : 'audio/mpeg',
    mp4         : 'video/mp4',
    mpeg        : 'video/mpeg',
    mpkg        : 'application/vnd.apple.installer+xml',
    mov         : 'video/quicktime',
    odp         : 'application/vnd.oasis.opendocument.presentation',
    ods         : 'application/vnd.oasis.opendocument.spreadsheet',
    odt         : 'application/vnd.oasis.opendocument.text',
    oga         : 'audio/ogg',
    ogv         : 'video/ogg',
    ogx         : 'application/ogg',
    opus        : 'audio/ogg',
    otf         : 'font/otf',
    pdf         : 'application/pdf',
    php         : 'application/x-httpd-php',
    png         : 'image/png',
    ppt         : 'application/vnd.ms-powerpoint',
    pptx        : 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    rar         : 'application/vnd.rar',
    rss         : 'application/rss+xml; charset=utf-8',
    rtf         : 'application/rtf',
    sh          : 'application/x-sh',
    svg         : 'image/svg+xml; charset=utf-8',
    tar         : 'application/x-tar',
    tif         : 'image/tiff',
    tiff        : 'image/tiff',
    ts          : 'video/mp2t',
    ttf         : 'font/ttf',
    txt         : 'text/plain; charset=utf-8',
    vsd         : 'application/vnd.visio',
    vtt         : 'text/vtt; charset=utf-8',
    wasm        : 'application/wasm',
    wav         : 'audio/wav',
    weba        : 'audio/webm',
    webm        : 'video/webm',
    webmanifest : 'application/manifest+json; charset=utf-8',
    webp        : 'image/webp',
    woff        : 'font/woff',
    woff2       : 'font/woff2',
    xhtml       : 'application/xhtml+xml; charset=utf-8',
    xls         : 'application/vnd.ms-excel',
    xlsx        : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    xml         : 'text/xml; charset=utf-8',
    xul         : 'application/vnd.mozilla.xul+xml; charset=utf-8',
    yaml        : 'application/yaml; charset=utf-8',
    yml         : 'application/yaml; charset=utf-8',
    zip         : 'application/zip',
    zst         : 'application/zstd'
});
